# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# While our "example" application has the platform-specific code,
# for simplicity we are compiling and testing everything on the Ubuntu environment only.
# For multi-OS testing see the `cross.yml` workflow.

on: [push, pull_request]


jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install deps
        run: sudo apt-get install -y wget libfuse-dev libgtk-3-dev

      - name: Run cargo check
        run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install deps
        run: sudo apt-get install -y wget libfuse-dev libgtk-3-dev

      - name: Run cargo test
        run: cargo test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install deps
        run: sudo apt-get install -y wget libfuse-dev libgtk-3-dev

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings


  build:
    needs:
      - check
      - test
      - lints
    runs-on: '${{ matrix.os }}'
    env:
      VERSION: ${{ github.ref }}
      REPOSITORY_NAME: 'metconst-tool'
    strategy:
      matrix:
        include:
          #- os: macos-latest
          #  target: metconst-tool-x86_64.macos
          #  artifact-path: ./target/release/metconst-tool.zip
          #  is-osx: 1
          #- os: macos-11
          #  target: metconst-tool-x86_64.macos-11
          #  artifact-path: ./target/release/metconst-tool.zip
          #  is-osx: 1
          #- os: macos-latest
          #  target: metconst-tool--aarch64.macos
          #  artifact-path: ./target/release/metconst-tool.zip
          #  is-osx: 1
          #- os: ubuntu-latest
          #  target: metconst-tool-x86_64.AppImage
          #  artifact-path: metconst-tool.AppImage
          #  is-linux: 1
          - os: windows-latest
            target: metconst-tool-x86_64.win
            artifact-path: ./target/release/metconst-tool.exe
            is-windows: 1
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Linux dependencies
        if: ${{ matrix.is-linux }}
        run: |
          sudo apt-get install -y wget libfuse-dev libgtk-3-dev
          cargo install --force cargo-appimage
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
          chmod a+x appimagetool
      - name: Apple arm tool chain
        if: ${{ matrix.target == 'metconst-tool-aarch64.macos' }}
        run: |
          export TARGET=aarch64-apple-darwin
          rustup target add $TARGET
      - run: cargo build --release
        #- run: cargo install --force cargo-strip
        #- run: cargo install --force cargo-bundle
        #- run: cargo strip -t release
      - name: macOS bundling
        if: ${{ matrix.is-osx }}
        run: |
          cargo bundle --release
          pushd target/release/bundle/osx
          zip -r metconst-tool.zip metconst-tool.app
          cp metconst-tool.zip ../../
          popd
      - name: Linux bundling
        if: ${{ matrix.is-linux }}
        run: |
          PATH=./:$PATH cargo appimage
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ${{ matrix.artifact-path }}
  release:
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master'
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - id: get_repository_name
        run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_OUTPUT
        shell: bash
          #- uses: actions/download-artifact@v3
          #  with:
          #    name: metconst-tool-x86_64.AppImage
          #    path: metconst-tool-x86_64.AppImage/
            #- uses: actions/download-artifact@v3
            #  with:
            #    name: metconst-tool-x86_64.macos
            #    path: metconst-tool-x86_64.macos/
            #- uses: actions/download-artifact@v3
            #  with:
            #    name: metconst-tool-aarch64.macos
            #    path: metconst-tool-aarch64.macos/
            #- uses: actions/download-artifact@v3
            #  with:
            #    name: metconst-tool-x86_64.macos-11
            #    path: metconst-tool-x86_64.macos-11/
      - uses: actions/download-artifact@v3
        with:
          name: metconst-tool-x86_64.win
          path: metconst-tool-x86_64.win/
      - id: get_commit_id
        run: echo SHORT_COMMIT_ID=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
        shell: bash
      - id: tag_date
        run: echo TAG_NAME=$(date +'%Y-%m-%d')-${{ steps.get_commit_id.outputs.short_commit_id }} >> $GITHUB_OUTPUT
        shell: bash
      - id: create_release
        #uses: elgohr/Github-Release-Action@v5
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_date.outputs.TAG_NAME }}
          release_name: metconst-tool Release ${{ steps.tag_date.outputs.TAG_NAME }}
          draft: ${{ github.ref != 'refs/heads/master' }}
          prerelease: true
            #- uses: actions/upload-release-asset@v1
            #  env:
            #    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
            #  with:
            #    upload_url: ${{ steps.create_release.outputs.upload_url }}
            #    asset_path: ./metconst-tool-x86_64.AppImage/metconst-tool-0.1.0-x86_64.AppImage
            #    asset_name: metconst-tool-${{ steps.tag_date.outputs.TAG_NAME }}-x86_64-linux.AppImage
            #    asset_content_type: application/octet-stream
            #- uses: actions/upload-release-asset@v1
            #  env:
            #    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
            #  with:
            #    upload_url: '${{ steps.create_release.outputs.upload_url }}'
            #    asset_path: ./metconst-tool-x86_64.macos/metconst-tool.zip
            #    asset_name: metconst-tool-${{ steps.tag_date.outputs.TAG_NAME }}-x86_64-macOS.zip
            #    asset_content_type: application/octet-stream
            #- uses: actions/upload-release-asset@v1
            #  env:
            #    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
            #  with:
            #    upload_url: '${{ steps.create_release.outputs.upload_url }}'
            #    asset_path: ./metconst-tool-aarch64.macos/metconst-tool.zip
            #    asset_name: metconst-tool-${{ steps.tag_date.outputs.TAG_NAME }}-aarch64-macOS.zip
            #    asset_content_type: application/octet-stream
            #- uses: actions/upload-release-asset@v1
            #  env:
            #    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
            #  with:
            #    upload_url: '${{ steps.create_release.outputs.upload_url }}'
            #    asset_path: ./metconst-tool-x86_64.macos-11/metconst-tool.zip
            #    asset_name: metconst-tool-${{ steps.tag_date.outputs.TAG_NAME }}-x86_64-macOS-11.zip
            #    asset_content_type: application/octet-stream
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          upload_url: '${{ steps.create_release.outputs.upload_url }}'
          asset_path: ./metconst-tool-x86_64.win/metconst-tool.exe
          asset_name: metconst-tool-${{ steps.tag_date.outputs.TAG_NAME }}-x86_64-windows.exe
          asset_content_type: application/octet-stream
